use anyhow::{Result, bail};

const MAX_GITHUB_COMMENT_BYTES: usize = 60_000;
const PROVENANCE: &str = "> Generated by Maid from a restricted Codex task.\n\n";

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GitHubComment(String);

impl GitHubComment {
    pub fn from_codex_response(response: &str) -> Result<Self> {
        let response = response.trim();
        if response.is_empty() {
            bail!("Codex produced an empty response");
        }
        if response.contains('\0') {
            bail!("Codex response contains a NUL byte");
        }

        let body = format!("{PROVENANCE}{}", neutralize_mentions(response));
        if body.len() > MAX_GITHUB_COMMENT_BYTES {
            bail!(
                "Codex response is too large to publish safely ({} bytes; maximum is {MAX_GITHUB_COMMENT_BYTES})",
                body.len()
            );
        }

        Ok(Self(body))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

fn neutralize_mentions(value: &str) -> String {
    value.replace('@', "@\u{200b}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn adds_provenance_and_neutralizes_github_mentions() {
        let comment = GitHubComment::from_codex_response("Review @team and @alice").unwrap();

        assert!(comment.as_str().starts_with(PROVENANCE));
        assert!(comment.as_str().contains("@\u{200b}team"));
        assert!(!comment.as_str().contains("@team"));
    }

    #[test]
    fn rejects_content_that_is_not_safe_to_publish() {
        assert!(GitHubComment::from_codex_response("  ").is_err());
        assert!(GitHubComment::from_codex_response("bad\0body").is_err());
        assert!(GitHubComment::from_codex_response(&"x".repeat(MAX_GITHUB_COMMENT_BYTES)).is_err());
    }
}
